### ISSUE TITLE
Quando uma rota sem permissão é acessada o usuário vai para o login da USP. Fazer o retorno (callback) ir para a última página visitada antes do redirecionamento. 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/pessoas#1]

**Comment by masakik** [comment]
Isso é feito guardando a url na sessão?

**Comment by thiagogomesverissimo** [comment]
isso, com a função back() em cada método do controller. Mas acho que não vale a pena o esforço nesse projeto...
Estou tentando achar uma solução global no laravel. Se achar, reabro essa issue.
