### ISSUE TITLE
Permitir servidor ou docente da unidade logar e ver informações básicas institucionais

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/pessoas#107]
Poderão ver informações básicas institucionais de servidores, docentes e docentes aposentados :
- Nome
- E-mail institucional
- Vínculo
- Setor ou Departamento
**Não mostrar a foto
Não adiciona informações**

**Comment by masakik** [comment]
Já teria um nome de gate para isso: seria uma permissão menor que secretaria.
Talvez pudessemos tentar ver uma nomenclatura boa para esse e outros gates

**Comment by masakik** [comment]
Acabou ficando basico e avancado. Feito #117. O avancado não permite gerenciar usuários. Para isso tem de ter a permissão admin.
