### ISSUE TITLE
exibir funcionários e docentes afastadas

### ISSUE THREAD

**Issue by ezanon** [uspdev/pessoas#120]
Um menu que liste pessoal afastado. Já fiz uma query que precisei aqui.

-- pessoas em férias ou outras situações de afastamento
select v.codpes as nusp, p.nompes as nome, v.sitoco as situacao, convert(varchar, v.dtafimsitoco, 103) as ateh from VINCULOPESSOAUSP v 
inner join PESSOA p on v.codpes = p.codpes
where 
--v.sitoco = 'Férias' and 
v.codund IN (44) and
v.dtafimsitoco > GETDATE()-1 
order by v.dtafimsitoco

**Comment by masakik** [comment]
Parece bom isso.

**Comment by alecostaweb** [comment]
Pensei em um item de menu "Afastados" ao lado de "Pós-Graduação" e na permission pessoas.avancado

**Comment by alecostaweb** [comment]
Novo método "listarAfastados" no uspdev/replicado

**Comment by alecostaweb** [comment]
SELECT V.codpes, V.nompes, S.nomabvset, V.sitoco, V.dtainisitoco, V.dtafimsitoco 
FROM VINCULOPESSOAUSP V INNER JOIN SETOR S ON V.codset = S.codset
WHERE V.codund IN (27) AND V.dtafimsitoco > GETDATE()-1
ORDER BY V.nompes
