### ISSUE TITLE
Exibir vínculos em outros setores dentro da unidade

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/pessoas#131]
Logo abaixo do card "Vínculos encerrados", exibir o novo card "Vínculos em outros setores da unidade" (não sei se é o melhor nome) no mesmo molde

Trazer as informações da tabela RESUSERVHISTFUNCIONAL (Resumo do histórico funcional dos Servidores)
-- nomabvset (sem '-codund'), nomset, nomfnc, (período)

SELECT R.* FROM RESUSERVHISTFUNCIONAL R WHERE R.codpes = $codpes AND R.dtafimsitfun IS NOT NULL 

Na consulta acima o vínculo ativo é descartado porque já é exibido em vínculos ativos.

Para isso será necessário um novo método no uspdev/replicado, listarVinculosEmOutrosSetores($codpes)

**Comment by alecostaweb** [comment]
Talvez o nome do card fique melhor com "Resumo do histórico funcional na unidade", até porque quando é docente também mostra informações

**Comment by masakik** [comment]
Acho que somente "Histórico funcional" já serve
