### ISSUE TITLE
interface para permitir o gerenciamento de usuarios 

### ISSUE THREAD

**Issue by masakik** [uspdev/pessoas#19]
Permitir que se cadastre um administrador do sistema (secretaria por ex) e essa pessoas poderia adicionar e remover outros usuários e definir quem pode cadastrar e remover, tipo admins eusers.

**Comment by masakik** [comment]
será que isso não poderia ser um projeto separado que teria uma view/model/controller que permitiria adicionar usuários e definir administradores?

**Comment by masakik** [comment]
Mas isso eu não sei fazer no laravel

**Comment by alecostaweb** [comment]
Interessante essa ideia, poderia ser algo do tipo:
https://github.com/jeremykenedy/laravel-users
Usando o replicado e também apontando quais sistemas locais o camarada teria acesso

**Comment by thiagogomesverissimo** [comment]
Tá feito há alguns meses.
