### ISSUE TITLE
Mostrar as informações em dois blocos, institucional e pessoal

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/pessoas#25]
![image](https://user-images.githubusercontent.com/10613364/59045361-4eac7200-8856-11e9-9b02-4b63730f4a08.png)

**Comment by alecostaweb** [comment]
O propósito seria que o que for institucional ser de domínio público (sem autenticação) inclusive o Nº USP. O que acham?

**Comment by masakik** [comment]
Parece bom. 👍

**Comment by masakik** [comment]
Lembrando que em outra issue o Thiago fala em aumentar os dados institucionais que seriam mostrados e alguns deles não seriam publicos.

**Comment by thiagogomesverissimo** [comment]
Podemos criar uma rota pública neste sistema que lista as pessoas com dados básicos. O sistema que você tem na ECA tem um parte pública @alecostaweb  ?

**Comment by alecostaweb** [comment]
Sim
http://www3.eca.usp.br/pessoa

**Comment by alecostaweb** [comment]
Ao trazer os dados mostrar tbm a foto com o uspdev/wsfoto
