### ISSUE TITLE
Exportar alunos de graduação, pós-graduação, funcionários, docentes ativos e docentes aposentados em csv

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/pessoas#3]

**Comment by thiagogomesverissimo** [comment]
usar filas do laravel para geração desses arquivos em background

**Comment by alecostaweb** [comment]
A ideia é o sistema fornecer listas para aqueles que logarem?

**Comment by thiagogomesverissimo** [comment]
sim. Exemplo: exportar rapidamente listas no excel/ods de docentes, funcionários, etc.

**Comment by alecostaweb** [comment]
Seria bom também, mas como o laravel-usp-theme tem link para sistemas externos, penso que fornecer estas listas no pessoas seria mais prático, inclusive tem issue aberta lá.

**Comment by thiagogomesverissimo** [comment]
Esse é o sistemas pessoas -)

**Comment by alecostaweb** [comment]
Sim, foi o que eu disse rs
