### ISSUE TITLE
Adicionar informação no readme sobre a permissão de escrita na pasta storage

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/pessoas#37]

**Comment by alecostaweb** [comment]
Tbm alterar o comando
php artisan:migrate
para
php artisan migrate

**Comment by masakik** [comment]
a pasta log também precisa ajustar permissão?

**Comment by alecostaweb** [comment]
Sempre que faço deploy tenho que adicionar permissão de escrita na pasta storage

**Comment by thiagogomesverissimo** [comment]
Isso está relacionado ao ambiente, no caso suponho apache. Podemos até colocar essa informação, mas como disse, isso depende do tipo de servidor usado na produção.

**Comment by masakik** [comment]
mesmo se for o nginx (eu não uso) não tem de dar permissão de escrita para o usuario que roda o processo dele?

**Comment by thiagogomesverissimo** [comment]
Depende do usuário dono dos arquivos. Se for www-data não há problema, pois automaticamente ele tem essa permissão. Mesmo usando php artisan serve só não dá problema pois estamos rodando um serve com o nosso próprio usuário. Se tiveram problema é porque não estão usando o usuário www-data, assim bastaria colocar esse usuário no grupo www-data. Mas claro, se estamos falando de um servidor compartilhado isso deve ser pensando de outra forma. Enfim, podemos colocar sim no readme essa informação, mas sempre vai depender da infra.

**Comment by masakik** [comment]
:+1:

**Comment by alecostaweb** [comment]
Aqui usando php artisan serve tenho que dar permissão na pasta
