### ISSUE TITLE
Modificar APP_URL no .env.example

### ISSUE THREAD

**Issue by leandroramos** [uspdev/pessoas#43]
Mudar APP_URL para http://localhost:8000, pois os links do menu ficam quebrados.
![image](https://user-images.githubusercontent.com/3253741/66161718-58c35f00-e603-11e9-9d30-85abca4eaf57.png)

Outra coisa que pode ser feita é orientar tal mudança no readme (eu acho melhor alterar o .env.example mesmo)

**Comment by alecostaweb** [comment]
No .env.example fica melhor mesmo. Minha opinião
