### ISSUE TITLE
Rebaixar versão do mockery no compsoer.lock

### ISSUE THREAD

**Issue by masakik** [uspdev/pessoas#63]
Lá está na versão 1.4.0 que pede php 7.3. Mas no composer.json tá ^1.3.1 que é compatível com php mais antigo.
Tem como não fixar isso no lock?

**Comment by masakik** [comment]
A versão atual é a 1.3.3 para compatibilidade

**Comment by thiagogomesverissimo** [comment]
Não consegui achar onde da problema. Eu acabei de mandar um commit que funcionou em php 7.4 e php 7.3.28
