### ISSUE TITLE
Se a pessoa nao tiver endereço cadastrado retorna erro no sistema

### ISSUE THREAD

**Issue by masakik** [uspdev/pessoas#64]
ErrorException
Trying to access array offset on value of type bool (View: /home/sistemas/pessoas/resources/views/pessoas/partials/show/replicado.blade.php)

**Comment by masakik** [comment]
É o caso de nossos alunos ingressantes da pos, que informam o endereço dois que tiverem um definitivo na cidade.

**Comment by thiagogomesverissimo** [comment]
Humm.. essa verificação deveria ser feita para qualquer campo.
