### ISSUE TITLE
Porque o title da aplicação é "dashboard"?

### ISSUE THREAD

**Issue by masakik** [uspdev/pessoas#73]
Não deveria pegar do app.name?

**Comment by thiagogomesverissimo** [comment]
Deveria...

**Comment by thiagogomesverissimo** [comment]
Na real, isso poderia ser direto no laravel usp theme

**Comment by masakik** [comment]
É que no tema tá @yield('title'). Poderia colocar direto o {{ $title }}.

**Comment by thiagogomesverissimo** [comment]
É bom deixar customizavel. É só trocar no tema de `@yield('title')` para `@section('title) config('app.name') @show`. Assim, quem quiser usar o default apontando para o nome da aplicação não precisa fazer nada. Quem quiser mudar,  basta sobreescrever a seção. Depois dessa mudança , neste sistema, o pessoas, somente apagamos a declaração da seção title, que automaticamente será usado o default da seção do tema pai, laravel usp theme.
