### ISSUE TITLE
Listar pessoas por departamento 

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/pessoas#77]
Ao "Buscar pessoas por departamento" 
Escolher um departamento em um campo Select2 
Listar as pessoas deste departamento 
Link nos nomes para exibir informações 
Considerar a hierarquia de setores e listar todas as pessoas abaixo 
Ao listar as pessoas trazer ao lado do nome os vínculos separados por vírgula

**Comment by alecostaweb** [comment]
@masakik estou pensando em vez de trazer hierarquia de setores, usar o select2 múltiplo, onde posso escolher informática e financeiro por exemplo. O que acha?

**Comment by masakik** [comment]
acho que fica legal. Sobre os setores abaixo, talvez tenha de colocar o setor na lsita também.
