### ISSUE TITLE
Na busca por nome

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/pessoas#78]
Trazer os vínculos separados por vírgula ao lado do nome

**Comment by alecostaweb** [comment]
@masakik e @thiagogomesverissimo 
Para adicionar as colunas Vínculos e Setores nos resultados da busca por nome é necessário utilizar os métodos Pessoa::vinculosSiglas e Pessoa::setoresSiglas, ambos precisam do codundclg. Sendo assim, no método Pessoa::procurarPorNome precisa incluir a coluna L.codundclg e um LEFT OUTER JOIN na tabela LOCALIZAPESSOA.
Testei aqui e na maioria dos casos só traz valores nas colunas para as pessoas com vínculo na unidade.
O objetivo é já nos resultados trazer os vínculos e setores das pessoas.
O que acham disso?

**Comment by thiagogomesverissimo** [comment]
Seria perfeito esse improve!
