### ISSUE TITLE
A pasta public/vendor/adminlte/ pode ser removida e public/vendor/adminlte/ deve ser colocada no .gitignore

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/pessoas#8]
Nas instruções de deploy do README.md inserir:
`php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets --force`

**Comment by girol** [comment]
@thiagogomesverissimo , essa instrução não faz nenhum sentido... só faz sentido publicar em `/public/vendor/adminlte/` se vc quiser modificar as views que o vendor fornece. Se vc não vai tocar nesses arquivos, não precisa publicar, nem ignorar, pq a classe já faz o instanciamento dos `blades` automaticamente

**Comment by thiagogomesverissimo** [comment]
No man!
A pasta /public/vendor/adminlte/ deve existir para o adminlte funcionar, os assets devem estar públicos. Mas não precisamos versioná-la.

**Comment by thiagogomesverissimo** [comment]
Perceba que não estou falando de views nem blade e sim de assets. :smile:

**Comment by girol** [comment]
Nossa maaaaaaaaaaaaan, MY BAD :man_facepalming:

**Comment by thiagogomesverissimo** [comment]
Só digo isso para você: :cat2:

**Comment by girol** [comment]
aseygaygeygaeauheuhauheuhaehuauheuhaehuas
