### ISSUE TITLE
enforce https inproduction

### ISSUE THREAD

**Issue by masakik** [uspdev/pessoas#99]
Da forma como está, se não for https não funciona.

**Comment by masakik** [comment]
e se colocar em uma config isso?

**Comment by thiagogomesverissimo** [comment]
Acho que seria uma solução boa colocar  no config/pessoas.php =)

**Comment by masakik** [comment]
Nos outros sistemas acontece o mesmo problema? De precisar forçar o https por estar atras de proxy?

**Comment by thiagogomesverissimo** [comment]
sim. Em todos sistema que temos no ar eu tive que colocar esse force. mas pode mudar, e eu configuro o .env
